"use client";
import { FormEvent, useEffect, useState } from "react";
type Service = { id: number; name: string; category: string; duration_minutes: number; price: number };
const today = () => new Date().toLocaleDateString("en-CA", { timeZone: "America/Santiago" });
export default function Reserve() {
  const [services, setServices] = useState<Service[]>([]), [professionals, setProfessionals] = useState<string[]>([]), [date, setDate] = useState(today()), [serviceId, setServiceId] = useState(""), [professional, setProfessional] = useState(""), [slots, setSlots] = useState<string[]>([]), [message, setMessage] = useState(""), [loading, setLoading] = useState(false);
  useEffect(() => { fetch("/api/public-booking").then(r => r.json()).then(data => { setServices(data.services ?? []); setProfessionals(data.professionals ?? []); }).catch(() => setMessage("No se pudieron cargar los servicios.")); }, []);
  useEffect(() => { if (!serviceId || !professional) { setSlots([]); return; } setLoading(true); fetch(`/api/public-booking?date=${date}&serviceId=${serviceId}&professional=${encodeURIComponent(professional)}`).then(r => r.json()).then(data => setSlots(data.slots ?? [])).finally(() => setLoading(false)); }, [date, serviceId, professional]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/public-booking", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...data, serviceId: Number(serviceId), date, professional }) }); const result = await response.json(); setMessage(result.ok ? "¡Solicitud recibida! Divas Beauty Spa confirmará tu hora por WhatsApp." : result.error); if (result.ok) event.currentTarget.reset(); }
  return <main className="booking-page"><section className="booking-card"><div className="brand"><span>✦</span><div>DIVAS<small>BEAUTY SPA</small></div></div><p className="eyebrow">RESERVA ONLINE · SANTIAGO</p><h1>Reserva tu momento Divas</h1><p className="subtle">Elige tu servicio y horario. Confirmaremos tu cita por WhatsApp.</p><form onSubmit={submit}><label>Nombre completo<input required name="clientName" placeholder="¿Cómo te llamas?"/></label><label>WhatsApp<input required name="phone" type="tel" placeholder="+56 9 ..."/></label><label>Servicio<select required value={serviceId} onChange={e => setServiceId(e.target.value)}><option value="">Selecciona un servicio</option>{services.map(service => <option key={service.id} value={service.id}>{service.name} · {service.duration_minutes} min</option>)}</select></label><div className="form-row"><label>Fecha<input required type="date" min={today()} value={date} onChange={e => setDate(e.target.value)}/></label><label>Profesional<select required value={professional} onChange={e => setProfessional(e.target.value)}><option value="">Selecciona</option>{professionals.map(name => <option key={name}>{name}</option>)}</select></label></div><label>Hora disponible<select required name="time" disabled={!slots.length}><option value="">{loading ? "Buscando horarios…" : "Selecciona una hora"}</option>{slots.map(slot => <option key={slot}>{slot}</option>)}</select></label><input className="honeypot" name="website" tabIndex={-1} autoComplete="off"/><button className="primary full">Solicitar reserva</button>{message && <p className="booking-message">{message}</p>}</form></section></main>;
}
